<?php

	function lockers_available($hold){
		$locations=\Drupal::state()>get('sopac_lockers_locations',array());
		$available=false;
		if($hold['status']==true or $hold['status']=="MEL RECIEVED"){
			if(stripos($hold['pickup'],'malletts')!==false){
				$locker_server = 'mcblockers';
			 }
			 else if(stripos($hold['pickup'],'pittsfield')){
			 	$locker_server = 'pittslockers'
			 }
			 if($locker_server){
			 	$ch = curl_init();
      			curl_setopt($ch, CURLOPT_URL, "http://".$locker_server."/mgr/p_insert.html");
      			curl_setopt($ch, CURLOPT_HEADER, 0);
      			curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
      			curl_setopt($ch, CURLOPT_USERPWD, "###########");
      			$result = curl_exec($ch);
      			preg_match_all('%name="web_patroninserted_door.*?value="([\d]+?)"%s', $result, $matches);
    		}
    	if ($matches[1][0] > 0) {
      		$available = TRUE;
    	  }
  		}
  		return $available;
	}

	

		//Mels included?
		//using redis?


?>